apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs.legiblequery.ai
spec:
  dnsNames:
    - docs.legiblequery.ai
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: legiblequery.ai-prod
  secretName: docs.legiblequery.ai-tls
