export enum MENU_KEY {
  QUESTION_SQL_PAIRS = 'question-sql-pairs',
  INSTRUCTIONS = 'instructions',
  API_HISTORY = 'api-history',
  API_USAGE = 'api-usage',
  API_BILLING = 'api-billing',
  QUERY_USAGE = 'query-usage',
  API_REFERENCE = 'api-reference',
  ROW_LEVEL_SECURITY = 'row-level-security',
  SESSION_PROPERTY = 'session-property',
  AGENTS = 'agents',
  AGENT_HUB = 'agent-hub',
  BLUEPRINTS = 'blueprints',
  BLUEPRINT_REGISTRY = 'blueprint-registry',
  GATEWAYS = 'gateways',
  AGENT_BUILDER = 'agent-builder',
  AGENT_BUILDER_PROMPT_TEMPLATES = 'agent-builder-prompt-templates',
  AGENT_BUILDER_TOOL_REGISTRY = 'agent-builder-tool-registry',
  AGENT_BUILDER_WORKFLOWS = 'agent-builder-workflows',
  AGENT_BUILDER_EXECUTION_HISTORY = 'agent-builder-execution-history',
  AGENT_BUILDER_AGENTS = 'agent-builder-agents',
  AGENT_BUILDER_AGENT_CHAT = 'agent-builder-agent-chat',
}
