/**
 * GraphQL route interception helpers for mock connector tests.
 *
 * Uses Playwright's page.route() to intercept /api/graphql requests
 * and return predefined responses, eliminating the need for real
 * database backends during connector form tests.
 */
import { Page } from '@playwright/test';
import { MOCK_TABLES, MOCK_RELATIONS } from './connectorFixtures';

/** Shape of a GraphQL POST body */
interface GraphQLBody {
  operationName?: string;
  query: string;
  variables?: Record<string, unknown>;
}

/**
 * Install GraphQL route mocks on a Playwright page.
 *
 * Intercepts POST /api/graphql and returns mock data for:
 *  - SaveDataSource → success with a new projectId
 *  - ListDataSourceTables → sample tables
 *  - AutoGeneratedRelations → sample relations
 *  - StartSampleDataset → success
 *
 * All other operations are passed through to the real server.
 */
export async function installGraphQLMocks(
  page: Page,
  opts: { projectId?: number } = {},
) {
  const projectId = opts.projectId ?? 99;

  await page.route('**/api/graphql', async (route) => {
    const request = route.request();
    if (request.method() !== 'POST') {
      return route.fallback();
    }

    let body: GraphQLBody;
    try {
      body = request.postDataJSON() as GraphQLBody;
    } catch {
      return route.fallback();
    }

    const opName = body.operationName || '';
    const queryText = body.query || '';

    // ── SaveDataSource ─────────────────────────────────────────
    if (opName === 'SaveDataSource' || queryText.includes('saveDataSource')) {
      const dsType = (body.variables?.data as any)?.type || 'DUCKDB';
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: {
            saveDataSource: {
              type: dsType,
              properties: {},
              projectId,
            },
          },
        }),
      });
    }

    // ── ListDataSourceTables ───────────────────────────────────
    if (
      opName === 'ListDataSourceTables' ||
      queryText.includes('listDataSourceTables')
    ) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: { listDataSourceTables: MOCK_TABLES },
        }),
      });
    }

    // ── AutoGeneratedRelations ─────────────────────────────────
    if (
      opName === 'AutoGeneratedRelations' ||
      queryText.includes('autoGenerateRelation')
    ) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: { autoGenerateRelation: MOCK_RELATIONS },
        }),
      });
    }

    // ── StartSampleDataset ─────────────────────────────────────
    if (
      opName === 'StartSampleDataset' ||
      queryText.includes('startSampleDataset')
    ) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: { startSampleDataset: true },
        }),
      });
    }

    // ── SaveTables (model selection) ───────────────────────────
    if (opName === 'SaveTables' || queryText.includes('saveTables')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: { saveTables: true },
        }),
      });
    }

    // ── SaveRelations (relationship selection) ─────────────────
    if (opName === 'SaveRelations' || queryText.includes('saveRelations')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: { saveRelations: true },
        }),
      });
    }

    // ── OnboardingStatus ───────────────────────────────────────
    if (
      opName === 'OnboardingStatus' ||
      queryText.includes('onboardingStatus')
    ) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: {
            onboardingStatus: {
              step: 'DATASOURCE_SAVED',
              __typename: 'OnboardingStatusResponse',
            },
          },
        }),
      });
    }

    // ── GetSettings / GetCurrentProject ────────────────────────
    if (
      opName === 'GetCurrentProject' ||
      queryText.includes('getCurrentProject')
    ) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: {
            getCurrentProject: {
              id: projectId,
              displayName: 'Mock Project',
              type: 'DUCKDB',
              __typename: 'Project',
            },
          },
        }),
      });
    }

    // Everything else → passthrough
    return route.fallback();
  });
}

/**
 * Remove all route interceptions (call in afterEach/afterAll).
 */
export async function removeGraphQLMocks(page: Page) {
  await page.unrouteAll({ behavior: 'ignoreErrors' });
}
